---
development:
  cloud_name: hhv50xuay
  api_key: '467595369249531'
  api_secret: WmKjrPKSw8T5gJ6gnwMpR66x7TA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hhv50xuay
  api_key: '467595369249531'
  api_secret: WmKjrPKSw8T5gJ6gnwMpR66x7TA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hhv50xuay
  api_key: '467595369249531'
  api_secret: WmKjrPKSw8T5gJ6gnwMpR66x7TA
  enhance_image_tag: true
  static_image_support: false
