# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8c34e6f8ec4aa4ef72fbeca67078796f6ad2460709bb3b28ee04619a3b06d482e6428e2517b353d5202fa17bf705be264810da182b1d3a38598a5ceb94a13b3

test:
  secret_key_base: 524a124aad82b1b07cb931972d516eae3ca7869670dcdbb76d9a52a80ec8b216eb2a1cee12f54307df2476ae2be738e70778788fb7ebc45ae307adefed5b9a28

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
